language:
  - python 3.6
  - ruby

branches:
  only:
  - pelican

sudo: required

install:
  - sudo pip install --upgrade pip
  - pip install pelican==4.0.1 --user

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: pelican
  target_branch: master
  local_dir: ${TRAVIS_BUILD_DIR}/output