language: node_js


env:
  - GH_REPO="https://$GITHUB_TOKEN@github.com/taciossbr/taciossbr.github.io.git"

# Adicione a branch onde está a instalação do Hexo
branches:
  only:
  - hexo

before_install:
- npm install -g hexo

install:
- npm install
- git clone https://github.com/probberechts/hexo-theme-cactus.git themes/cactus

# Configure seu nome de usuário e e-mail
before_script:
- git config --global user.name 'taciossbr'
- git config --global user.email 'tacioss.br@gmail.com'


script:
- hexo generate

# Configure a Branch a ser feito o deploy
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $GH_REPO . || (git init && git remote add -t master origin $GH_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m master
- git push -q -u origin master









# -----------------------------------


# language:
#   - python 3.6

# branches:
#   only:
#   # - pelican
#   - hexo

# sudo: required

# install:
#   - sudo pip install --upgrade pip
#   - pip install pelican==4.0.1 --user
#   - pip install ghp-import==0.5.5 --user
#   - pip install Markdown==3.0.1 --user
#   - git clone https://github.com/gilsondev/pelican-clean-blog.git themes/pelican-clean-blog/

# script:
#   - make publish

# after_success:

#   - make github